spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/api-gateway?createDatabaseIfNotExist=true
    username: gateway
    password: gateway
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  salt: ygvbimuhergt
  jwt:
    access-minutes: 180
    secret: henifdcbogloejkoiurkfvscfkbpimjgntytjtvkotgfkjerdtfvuyhjioklmjnbhhfcdrtyuhjikfdy
  response-ttl-minutes: 5
  rate-limit:
    perMinute: 100
    perHour: 1000