spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/api-gateway?createDatabaseIfNotExist=true
    username: gateway
    password: gateway
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: admin
  jackson:
    default-property-inclusion: non_null

app:
  salt: ygvbimuhergt
  jwt:
    access-minutes: 180
    secret: henifdcbogloejkoiurkfvscfkbpimjgntytjtvkotgfkjerdtfvuyhjioklmjnbhhfcdrtyuhjikfdy
  response-ttl-minutes: 5
  rate-limit:
    perMinute: 10
    perHour: 100
  healthCheckJobSeconds: 120
  upstreamTimeoutSeconds: 20

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024