version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-gateway
      MYSQL_USER: gateway
      MYSQL_PASSWORD: gateway
    ports:
      - "3306:3306"